server:
  port: 9090

jwt:
  header: Authorization   #http请求头所需要的字段
  sercet: mySercet        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key